### PR TITLE
Added IPv6 SLAAC support

### PR DESCRIPTION
**Pull request by feldsam**
also fixed example hook config

### CODE REVIEW

**Comment by atodorov-storpool** [comment]
Thanks for the update @feldsam !

I'll update the comments regarding the hook config example. The reasoning for it is following.

I am patching the _HM_MAD_ to send the VM template via _STDIN_ when `$TEMPLATE` variable is prefixed with `-i` argument. On a fat VM with a lot of aliases (imagine a shared hosting VM scenario), the hooks are failing because of "argument string too long" error. The live migration is failing with same reason too. You can find my patches for hook and transfer mads in [patches/mads/5.8.1](https://github.com/OpenNebula/addon-storpool/tree/master/patches/mads/5.8.1)

Regarding the `$DEBUG` variable - I am lazy so I am testing against "anything" in the _DEBUG_ variable to trigger the debug. That's why it is commented out (`DEBUG=0` will trigger the debug logs too ;)).

**Comment by feldsam** [comment]
Hi, thanks for info. I am looking into you patch. Why not just use

`cmd=LocalCommand.run(cmd_string, log_method(number), arguments.join(' '))` without doing IFs and -i arg.

**Comment by atodorov-storpool** [comment]
As it is a not official hack, it could interfere with other 3rd party hooks that does not expect/support the template via stdin...
Anyway in 5.10 the VM $TEMPLATE will be passed via stdin, so hopefully this script should live 'till release of 5.10...

**Comment by feldsam** [comment]
do you have commit hash in master where is change regarding this? So I can backport it instead of using patch. Thanks

**Comment by atodorov-storpool** [comment]
the hook manager is entirely re-written - separate service, more powerful... I've just looked how to fix this issue. Most close patch is for VNM_MAD, that is what I've used for hints: https://github.com/OpenNebula/one/commit/8121175b6e03aaa0c4c973416d1356fbf6fa24cd

**Comment by feldsam** [comment]
ok, I use you actual pach :) hopefully, there will be soon work on pre|post|clean_alias method in vnn.

**Comment by atodorov-storpool** [comment]
TM_MAD is fixed with thiss issue https://github.com/OpenNebula/one/pull/3374
HM_MAD (my patch that was dropped because it will be entirely re-written) https://github.com/OpenNebula/one/issues/3369

**Comment by feldsam** [comment]
I see, so I need both patches applied

**Pull request merged**
